-- ----------------------------
-- Records of provinces
-- ----------------------------
INSERT INTO `provinces` VALUES (1, 10, 'กรุงเทพมหานคร', 'Bangkok', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (2, 11, 'สมุทรปราการ', 'Samut Prakarn', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (3, 12, 'นนทบุรี', 'Nonthaburi', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (4, 13, 'ปทุมธานี', 'Pathum Thani', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (5, 14, 'พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (6, 15, 'อ่างทอง', 'Ang Thong', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (7, 16, 'ลพบุรี', 'Lop Buri', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (8, 17, 'สิงห์บุรี', 'Sing Buri', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (9, 18, 'ชัยนาท', 'Chai Nat', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (10, 19, 'สระบุรี', 'Saraburi', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (11, 20, 'ชลบุรี', 'Chon Buri', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (12, 21, 'ระยอง', 'Rayong', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (13, 22, 'จันทบุรี', 'Chanthaburi', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (14, 23, 'ตราด', 'Trat', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (15, 24, 'ฉะเชิงเทรา', 'Chachoengsao', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (16, 25, 'ปราจีนบุรี', 'Prachin Buri', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (17, 26, 'นครนายก', 'Nakhon Nayok', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (18, 27, 'สระแก้ว', 'Sa kaeo', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (19, 30, 'นครราชสีมา', 'Nakhon Ratchasima', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (20, 31, 'บุรีรัมย์', 'Buri Ram', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (21, 32, 'สุรินทร์', 'Surin', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (22, 33, 'ศรีสะเกษ', 'Si Sa Ket', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (23, 34, 'อุบลราชธานี', 'Ubon Ratchathani', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (24, 35, 'ยโสธร', 'Yasothon', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (25, 36, 'ชัยภูมิ', 'Chaiyaphum', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (26, 37, 'อำนาจเจริญ', 'Amnat Charoen', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (27, 38, 'บึงกาฬ', 'Bueng Kan', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (28, 39, 'หนองบัวลำภู', 'Nong Bua Lam Phu', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (29, 40, 'ขอนแก่น', 'Khon Kaen', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (30, 41, 'อุดรธานี', 'Udon Thani', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (31, 42, 'เลย', 'Loei', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (32, 43, 'หนองคาย', 'Nong Khai', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (33, 44, 'มหาสารคาม', 'Maha Sarakham', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (34, 45, 'ร้อยเอ็ด', 'Roi Et', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (35, 46, 'กาฬสินธุ์', 'Kalasin', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (36, 47, 'สกลนคร', 'Sakon Nakhon', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (37, 48, 'นครพนม', 'Nakhon Phanom', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (38, 49, 'มุกดาหาร', 'Mukdahan', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (39, 50, 'เชียงใหม่', 'Chiang Mai', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (40, 51, 'ลำพูน', 'Lamphun', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (41, 52, 'ลำปาง', 'Lampang', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (42, 53, 'อุตรดิตถ์', 'Uttaradit', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (43, 54, 'แพร่', 'Phrae', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (44, 55, 'น่าน', 'Nan', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (45, 56, 'พะเยา', 'Phayao', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (46, 57, 'เชียงราย', 'Chiang Rai', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (47, 58, 'แม่ฮ่องสอน', 'Mae Hong Son', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (48, 60, 'นครสวรรค์', 'Nakhon Sawan', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (49, 61, 'อุทัยธานี', 'Uthai Thani', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (50, 62, 'กำแพงเพชร', 'Kamphaeng Phet', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (51, 63, 'ตาก', 'Tak', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (52, 64, 'สุโขทัย', 'Sukhothai', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (53, 65, 'พิษณุโลก', 'Phitsanulok', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (54, 66, 'พิจิตร', 'Phichit', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (55, 67, 'เพชรบูรณ์', 'Phetchabun', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (56, 70, 'ราชบุรี', 'Ratchaburi', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (57, 71, 'กาญจนบุรี', 'Kanchanaburi', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (58, 72, 'สุพรรณบุรี', 'Suphan Buri', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (59, 73, 'นครปฐม', 'Nakhon Pathom', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (60, 74, 'สมุทรสาคร', 'Samut Sakhon', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (61, 75, 'สมุทรสงคราม', 'Samut Songkhram', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (62, 76, 'เพชรบุรี', 'Phetchaburi', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (63, 77, 'ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (64, 80, 'นครศรีธรรมราช', 'Nakhon Si Thammarat', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (65, 81, 'กระบี่', 'Krabi', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (66, 82, 'พังงา', 'Phang-nga', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (67, 83, 'ภูเก็ต', 'Phuket', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (68, 84, 'สุราษฎร์ธานี', 'Surat Thani', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (69, 85, 'ระนอง', 'Ranong', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (70, 86, 'ชุมพร', 'Chumphon', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (71, 90, 'สงขลา', 'Songkhla', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (72, 91, 'สตูล', 'Satun', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (73, 92, 'ตรัง', 'Trang', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (74, 93, 'พัทลุง', 'Phatthalung', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (75, 94, 'ปัตตานี', 'Pattani', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (76, 95, 'ยะลา', 'Yala', 1, NULL, NULL);
INSERT INTO `provinces` VALUES (77, 96, 'นราธิวาส', 'Narathiwat', 1, NULL, NULL);
